# -*- coding: utf-8 -*-
"""week4_lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZdK8BlI9AhBHC8zQBNqMDcW54GQY10WR
"""

class Node:
    
    def __init__(self, key):
        self.key = key
        self.left = None
        self.right = None

class BinarySearchTree:
    
    def __init__(self):
        self.root = None
    
    def insert(self, current_node, key):
        ## Insert a new node with given key to bst 
        """
        Input:  current_node, key
        Output: None
        """   
        if self.root == None:
            self.root = Node(key)
            
        elif not self.search(self.root, key):
            if current_node.key > key:
        
                if current_node.left != None:
                    self.insert(current_node.left, key)
                else:
                    current_node.left = Node(key)                

            elif current_node.key < key:
               
                if current_node.right != None:
                    self.insert(current_node.right,key)
                else:
                    current_node.right = Node(key)
                
    
    def search(self, current_node, key):
        ## Search a given key in bst 
        """
        Input:  current_node, key
        Output: return False if key is not in bst
                return the node if key is in bst
        """
        if self.root == None:
            return False
            
        elif current_node.key == key:
            return current_node
        
        elif current_node.key > key and current_node.left:
            
            self.search(current_node.left,key)
            
        elif current_node.key < key and current_node.right:
            
            self.search(current_node.right,key)



    def delete(self, current_node, key):
        if self.root == None:
            print('nothing to delete')
        if current_node.key == key:
            if self.isChild(current_node) == 0:
                current_node = None
                
            if self.isChild(current_node) == 1:
                if current_node.right:
                    current_node = current_node.right
                else:
                    current_node = current_node.left
                    
            if self.isChild(current_node) == 2:

                prevnode = current_node
                chilnode = current_node.right
                while current_node.left:
                    prevnode = chilnode
                    chilnode = chilnode.left
                chilnode.right = current_node.right
                chilnode.left = current_node.left
                current_node = chilnode

        else:
            
            if current_node.key > key and current_node.left:
                self.delete(current_node.left,key)
            if current_node.key < key and current_node.right:
                self.delete(current_node.right,key)
            else:
                print('nothing to delete')


    def isChild(self, current_node):
        
        if (current_node.left == None) or (current_node.right == None):
            if (current_node.left == None) and (current_node.right == None):
                return 0
            else:
                return 1
            
        if current_node.left != None and current_node.right != None :
            return 2

        
    def preorder(self, node):
        ## Completed Funtion - DO NOT REMOVE
        ## Display key(s) of the bst in preorder
        if node:
            print(node.key, end=" ")
            self.preorder(node.left)
            self.preorder(node.right)
            

def main():
    
    bst1 = BinarySearchTree()
    bst1.insert(bst1.root, 60)
    bst1.insert(bst1.root, 25)
    bst1.insert(bst1.root, 100)
    bst1.insert(bst1.root, 35)
    bst1.insert(bst1.root, 17)
    bst1.insert(bst1.root, 80)
    #bst1.delete(bst1.root, 17)
    bst1.preorder(bst1.root)

    print()
    
    bst2 = BinarySearchTree()
    bst2.insert(bst2.root, "stupid")
    bst2.insert(bst2.root, "in")
    bst2.insert(bst2.root, "love")
    bst2.insert(bst2.root, "by")
    bst2.insert(bst2.root, "mad")
    bst2.insert(bst2.root, "clown")
    bst2.insert(bst2.root, "and")
    bst2.insert(bst2.root, "soyou")
    bst2.preorder(bst2.root)
    
main()
