# -*- coding: utf-8 -*-
"""week3_lab2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H_y97uVQe9HXE6s2UzXosIQsBTIC2OXK
"""
#나는 front가 가장 앞의 원소가 아니라 가장 앞의 원소 바로 앞을 의미하게 나타냈다

class CircularQueue:
    
    def __init__(self, size):
        self.size = size
        self.queue = [None] * size
        self.front = -1
        self.rear = -1

    def is_empty(self):
        ## Check if queue is empty
        if self.front == self.rear:
            return True
        else:
            return False
       
    def is_full(self):
        ## Check if queue is full
        if (self.rear+1)%self.size == (self.front+1)%self.size:
            if self.rear == -1 and self.front == -1:
                return False
            else:
                return True
        else:
            return False
                
    def enqueue(self, item):
        ## Insert an element at the back of the queue
        if self.is_full():
            print("Cannot Enqueue Full Queue!")
        else:
            self.rear = (self.rear+1)%self.size
            self.queue[self.rear] = item
               
    def dequeue(self):
        ## Remove the element at the front of the queue
        if self.is_empty():
            print("Cannot Remove Empty Queue!")
        else:
            self.front = (self.front+1)%self.size
            self.queue[self.front] = None
        
    def peek(self):
        ## Retrieve the front element of the queue
        if self.is_empty():
            print("No element Empty Queue!")
        else:
            return self.queue[(self.front+1)%self.size]
        
    def display(self):
        ## Completed Funtion - DO NOT REMOVE
        ## Display value(s) of the queue
        if self.is_empty():
            print("Empty Queue !")
            
        else:
            print(self.queue)
        
def main():
    queue = CircularQueue(6)
    print(queue.is_empty())
    queue.enqueue("Queue")
    queue.enqueue("is")
    queue.enqueue("simple")
    queue.display() # Expected Result: ['Queue', 'is', 'simple', None, None, None]
    
    queue.enqueue("Are")
    queue.enqueue("you")
    queue.enqueue("sure")
    queue.enqueue("?") # Expected Result: Cannot Enqueue Full Queue !
    queue.display() # Expected Result: ['Queue', 'is', 'simple', 'Are', 'you', 'sure']
    
    queue.dequeue()
    print("function peek():",queue.peek()) # Expected Result: function peek(): is
    queue.dequeue()
    queue.display() # Expected Result: [None, None, 'simple', 'Are', 'you', 'sure']
    
    queue.dequeue()
    queue.dequeue()
    queue.dequeue()
    queue.dequeue()
    queue.dequeue() # Expected Result: Cannot Remove Empty Queue !
    queue.peek() # Expected Result: No element Empty Queue !
    
main()

